[window]
opacity = 0.9

[general]
import = [
    "~/.config/alacritty/themes/themes/carbonfox.toml"
]

[font]
size = 10

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"
style = "Regular"

[font.bold]
family = "CaskaydiaCove Nerd Font Mono"
style = "Bold"

[font.italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Italic"

[scrolling]
history = 1000
multiplier = 3

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[env]
TERM = "xterm-256color"
